### PR TITLE
Spout relaunch only when needed

### PR DESCRIPTION
**Pull request by sir-maniac**
- only relaunches when max memory size is wrong
- added a -norelaunch option for special cases, with an error message
  when size is less then prefered size.

Fixes Jira Issue: http://issues.spout.org/browse/LAUNCHER-10

Signed-off-by: Sir Maniac sir.manic@gmail.com

### CODE REVIEW

**Comment by sir-maniac** [comment]
Got the Jira link wrong in the original request, edited it to the right one:
issue: http://issues.spout.org/browse/LAUNCHER-10

**Comment by lukespragg** [comment]
@nallar, usually Signed-off-by: Sir Maniac sir.manic@gmail.com means it has been done. ;)

**Comment by stephenwilliams** [comment]
Thanks!

**Comment by sir-maniac** [comment]
I hope that that was the way to sign off, it you need me to do something else to agree to your terms I'll do that.

**Comment by LunNova** [comment]
@sir-maniac
It was correct, I just forgot that the commit list for a PR only shows the first line, even if there's only one commit. :(

**Pull request merged**
