### PR TITLE
Render helmet as well as the player's head.

### PR DESCRIPTION
**Pull request by aarontwf**
Some skins don't look too good without their helmets on :).

Also it may be a good idea to call the <code>https://minotar.net/refresh/ + user</code> URL to refresh the player's skin each time the launcher is opened.

### CODE REVIEW

**Comment by lukespragg** [comment]
We aren't going to keep using minotar forever. It'll eventually be using our own, and providing a way to handle HD heads as well via our URLs.

**Comment by aarontwf** [comment]
Will you still consider doing both of these for now?

**Comment by lukespragg** [comment]
I don't see why not. :panda_face:

**Comment by Afforess** [comment]
Out of curiosity, do you know a user who's helmet makes that big a difference? I see none in my avatar.

**Comment by aarontwf** [comment]
My friend jkjoka:

https://minotar.net/avatar/jkjoka
https://minotar.net/helm/jkjoka

**Pull request merged**
