### PR TITLE
Fix allowing users to click out of the options/update dialogs

### PR DESCRIPTION
**Pull request by Zidane**
This sets the Modality Mode from Modeless to Application_Modal. Before you pull this Afforess or whoever, please test this first to make sure the same effect happens for you.

If not then let me know in the irc and we can work out whatever comes up

### CODE REVIEW

**Comment by Zidane** [comment]
Apparently this setting causes the options dialog to be EXTREMELY small when you first open it. If you close the dialog by hitting the "x" then open it back up, it shows as intended as well as prevents the user from clicking out of it (the purpose of this pull).

I am stumped...anyone have any ideas what could cause this?

**Comment by Top-Cat** [comment]
Also if you minimise both and restore, only the options screen comes back, not both.

**Comment by lukespragg** [comment]
The original issue isn't a problem anymore, but the way @Afforess changed it to doesn't allow the Options to be minimized at all. :/ It would be nice if the Options window minimized with the launcher, but stay on stop of it.

**Comment by Zidane** [comment]
I am actually still able to click "login" while the options menu is open (which is what I was trying to fix here).

Maybe more googling on modality mode is needed.

**Pull request merged**
