### PR TITLE
Fixing Forget for 2nd user

### PR DESCRIPTION
**Pull request by krosk93**
Forget1 != Forget2

### CODE REVIEW

**Comment by robxu9** [comment]
This commit was reverted in 7afa3c3803cb78b3afe936717db00fdc0dc8c4a1. [_Why was it reverted?_](https://github.com/SpoutDev/SpoutcraftLauncher/commit/7afa3c3803cb78b3afe936717db00fdc0dc8c4a1)

@Zidane, you may want to notify people when you revert their commits.

**Comment by Afforess** [comment]
Thanks for pointing this bug out though, I'll push a fix.

**Comment by Zidane** [comment]
@robxu9 

Next time read the commit log for the revert. I clearly tagged this user and explained why :).

**Comment by krosk93** [comment]
@Afforess that's just what I wanted, if you read irc logs, tonight I have left you a message in #spoutdev asking you to see the PR and fix it because I wasn't going to sign it. Thanks for fixing it!

**Comment by Afforess** [comment]
No problem, and thanks for bringing it to my attention. It was my fault for being lazy and not using constants, which I have now corrected.

**Pull request merged**
