### PR TITLE
non-premium user support

### PR DESCRIPTION
**Pull request by xenni**
Added support for non-premium users. Warns about potential server authentication problems and minecraft update failures.

### CODE REVIEW

**Comment by Top-Cat** [comment]
How about no.
We don't and will never support people who can't fork out the tiny amount of money minecraft costs.

**Comment by xenni** [comment]
Okay. Sorry.

Would you at least be interested in supporting some sort of offline-mode 
feature, like there is for the official server?
I could write that up really quick.

```
-Xenni
```

-----Original Message-----

**Comment by Top-Cat** [comment]
If it is based upon the user having to have previously authed, similar to steam offline mode.

**Comment by Afforess** [comment]
Offline mode that is identical to the Minecraft launcher offline mode is fine. But anything beyond that is not. This isn't our decision, we are just doing it so we don't get sued into the ground:

http://www.minecraft.net/terms

**Comment by Top-Cat** [comment]
The mc launcher requires you to have previously authed...

**Pull request closed without merging**
